### ISSUE TITLE
Remove the spawn menu.

### ISSUE THREAD

**Issue by D-113CR** [simpolmodmfs/simplemod-src#1]
You did not ask permission for use of the spawn menu. You have 24 hours to remove it before being faced with a DMCA strike. Comply or be taken down.
![image](https://github.com/user-attachments/assets/9e947ed2-010a-4700-adb0-bd38f4327c0a)

**Comment by christian-combine** [comment]
tell that to dim1xs lmao

**Comment by ThePixelMoon** [comment]
alt detected
