### ISSUE TITLE
Sorry for being a smartass again

### ISSUE THREAD

**Issue by Anjo2807** [simpolmodmfs/simplemod-src#10]
I think you forgot to add the thirdpartylegalnotices.txt file.

Sincerely, Anjo.

**Comment by ThePixelMoon** [comment]
Dear Anjo,
~~Go fuck yourself.~~ I'll ask the creator to add it.

Sincerely, A Person.

**Comment by Anjo2807** [comment]
ok wtf. im trying to be nice here

**Comment by ThePixelMoon** [comment]
that was a joke lmao

**Comment by ThePixelMoon** [comment]
![image](https://github.com/user-attachments/assets/664af3d9-cc76-4e4d-adc0-2f39d231b46e)
he still didnt answer

**Comment by Anjo2807** [comment]
im closing cuz he added stuff into it, like 3 months ago
