### ISSUE TITLE
Remove the spawn menu.

### ISSUE THREAD

**Issue by skibidi777toilet** [simpolmodmfs/simplemod-src#3]
You did not ask permission for use of the spawn menu. You have 24 hours to remove it before being faced with a DMCA strike. Comply or be taken down.
![387704854-39c8e274-b04f-43fe-8ae5-d97233e4176c](https://github.com/user-attachments/assets/1191f249-3ead-478c-ba37-f1db520c6993)

**Comment by ThePixelMoon** [comment]
alt detected
