### ISSUE TITLE
Copyright infringement issues

### ISSUE THREAD

**Issue by NotBart** [simpolmodmfs/simplemod-src#5]
This project encourages its participants to use stolen code. 
![image](https://github.com/user-attachments/assets/c049adfb-ea18-41f5-b9e1-513d11e552aa)

**Comment by christian-combine** [comment]
dude

**Comment by christian-combine** [comment]
theres no jbmod shit in my code

**Comment by NotBart** [comment]
That's not what I'm saying. Read the issue over again and think. You are very incompetent for a project lead!

**Comment by Anjo2807** [comment]
> theres no jbmod shit in my code

you should research my guy

**Comment by christian-combine** [comment]
bruh

**Comment by christian-combine** [comment]
most normal jbmod fans

**Comment by vlynkx** [comment]
> > theres no jbmod shit in my code
> 
> you should research my guy
https://youtu.be/aaBm7IJrLXo
he was the one who make the smenu and he did not complain about it,whats wrong with this stupid ahhh jbmod fanboy

**Comment by NotBart** [comment]
You all have the English language skills of an 8 year old. Are you sure you didn't plagiarize more?

**Comment by Abdul-T-Albaker** [comment]
stealing code from an already unpopular mod is crazy

**Comment by Abdul-T-Albaker** [comment]
grow a sack and make your own stuff

**Comment by christian-combine** [comment]
how did i steal code

**Comment by christian-combine** [comment]
man what the shit

**Comment by Abdul-T-Albaker** [comment]
by uploading the jbmod spawnmenu on your github

**Comment by christian-combine** [comment]
many other mods use the jbmod spawnmenu

**Comment by christian-combine** [comment]
+ i dont include it in releases fags

**Comment by vlynkx** [comment]
> by uploading the jbmod spawnmenu on your github

problematic ass😭
its just a spawn menu and christian combine says it was "jbmod spawn menu" not "simple mod spawn menu" these fanboy of jbmod is so problem asf😭

**Comment by christian-combine** [comment]
real

**Comment by NotBart** [comment]
> many other mods use the jbmod spawnmenu

That is incorrect.

**Comment by christian-combine** [comment]
then what

**Comment by christian-combine** [comment]
guest sandbox , etc used it

**Comment by vlynkx** [comment]
js ignore this stupid ahh jbmod fanboy,they always sucked jb55 diks

**Comment by Anjo2807** [comment]
ok what the fuck is wrong with you

**Comment by Anjo2807** [comment]
combine, what is wrong with you

**Comment by Anjo2807** [comment]
> js ignore this stupid ahh jbmod fanboy,they always sucked jb55 diks

no we don't

**Comment by christian-combine** [comment]
i just make it an addon

**Comment by christian-combine** [comment]
SO PPL COULD SPAWN SHIT

**Comment by christian-combine** [comment]
![image](https://github.com/user-attachments/assets/69a15510-4ba1-4ba6-af55-133b4c3ced49)

**Comment by Abdul-T-Albaker** [comment]
stop playing victim bruh

**Comment by christian-combine** [comment]
man

**Comment by christian-combine** [comment]
https://www.youtube.com/watch?v=EVHvuYvN_o4&t=11s

**Comment by christian-combine** [comment]
tell this mf same shit

**Comment by D-113CR** [comment]
### **JBmod Spawn Menu is proprietary code made by JBMan, inspired by Hds46's version which can be used on other mods. Further versions of the JBMod spawn menu shall include DRM that bricks other mods. GLORY TO JBMOD JB55 AND SNAKEZ OORAH!**

**Comment by christian-combine** [comment]
![image](https://github.com/user-attachments/assets/b9ddf248-8d13-4287-a054-63e16eccf002)

**Comment by Anjo2807** [comment]
![image](https://github.com/user-attachments/assets/6dbdddfd-599c-4c12-97e0-cca981899105)

**Comment by Anjo2807** [comment]
> ![image](https://private-user-images.githubusercontent.com/183110586/387715287-b9ddf248-8d13-4287-a054-63e16eccf002.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMjk2NTEsIm5iZiI6MTczMjAyOTM1MSwicGF0aCI6Ii8xODMxMTA1ODYvMzg3NzE1Mjg3LWI5ZGRmMjQ4LThkMTMtNDI4Ny1hMDU0LTYzZTE2ZWNjZjAwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOVQxNTE1NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMmQ0NDEzMWJkZjgxZWI2YjQyODUxMDU0NGUzNGM0YWY3ZjUxZGEwNGQ4YTk1NzliZDIyYjQ5NmE0NDNjMzRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.oVhx5HF6fJ_MTzZt2D7PmrWT93Drim93LWTlekZxK1M)

bro you are getting screwed
