### ISSUE TITLE
Stolen Code from JBMod.

### ISSUE THREAD

**Issue by skibidi777toilet** [simpolmodmfs/simplemod-src#6]
This project encourages its participants to use stolen code.
![Uploading 387704854-39c8e274-b04f-43fe-8ae5-d97233e4176c.png…]()

**Comment by christian-combine** [comment]
I DONT USE JBMOD CODE FOR FUCKS SAKE

**Comment by Anjo2807** [comment]
> I DONT USE JBMOD CODE FOR FUCKS SAKE

explain the screenshot

**Comment by christian-combine** [comment]
i removed that from the addons channel happy now?

**Comment by Anjo2807** [comment]
> i removed that from the addons channel happy now?

👍
