### ISSUE TITLE
make your own spawnmenu

### ISSUE THREAD

**Issue by Anjo2807** [simpolmodmfs/simplemod-src#7]
pls make your own spawnmenu, its easy

**Comment by ThePixelMoon** [comment]
i'd like to see you make one lol

**Comment by vlynkx** [comment]
> pls make your own spawnmenu, its easy

bet u cant make one lmaooo

**Comment by Anjo2807** [comment]
> > pls make your own spawnmenu, its easy
> 
> bet u cant make one lmaooo

bro, make it. idc
