### ISSUE TITLE
The Source SDK license is missing

### ISSUE THREAD

**Issue by Anjo2807** [simpolmodmfs/simplemod-src#8]
The lack of the Source SDK license can get you in legal trouble. please add it.

Sincerely, Anjo

**Comment by christian-combine** [comment]
aah okej

**Comment by ThePixelMoon** [comment]
look in hl2sb source code

**Comment by ThePixelMoon** [comment]
smartass

**Comment by mvoolt** [comment]
https://github.com/ValveSoftware/source-sdk-2013/blob/master/LICENSE
https://github.com/ValveSoftware/source-sdk-2013/blob/master/thirdpartylegalnotices.txt
>  You may copy, modify, and distribute the SDK and any modifications you make to the 
> SDK in source and object code form, but only for free.  Any distribution of this SDK must 
> include this LICENSE file and thirdpartylegalnotices.txt.  
No one can avoid not including this, every Source Engine mod is built upon the released SDK by Valve

**Comment by Anjo2807** [comment]
> look in hl2sb source code

well its not the reason to not include it

**Comment by Anjo2807** [comment]
btw the thing is getting dmca'ed by valve

**Comment by Anjo2807** [comment]
the repository and the mod

**Comment by ThePixelMoon** [comment]
holy yappings of the yappingtons
