### ISSUE TITLE
COPYRIGHT INFRINGEMENT ALERT

### ISSUE THREAD

**Issue by D-113CR** [simpolmodmfs/simplemod-src#9]
Not including the license of the Source SDK is a direct copyright infringement and illegal.

>   You may copy, modify, and distribute the SDK and any modifications you make to the 
> SDK in source and object code form, but only for free.  Any distribution of this SDK must 
> include this LICENSE file and thirdpartylegalnotices.txt.

**Comment by ThePixelMoon** [comment]
mr alt account master go check the hl2sb source code

**Comment by Anjo2807** [comment]
too late bruh i told them

**Comment by christian-combine** [comment]
leave me alone

**Comment by christian-combine** [comment]
yall did this over an addon

**Comment by Anjo2807** [comment]
> yall did this over an addon

yup, cuz you stole someones addon

**Comment by christian-combine** [comment]
ahh just fuck this im privating the code
